init:
  # Set autocrlf to make batch files work
  - git config --global core.autocrlf true
  # Start remote desktop  ( xfreerdp /v:<host>:<port> /u:<user> )
  #- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

clone_depth: 5

platform:
  - x64

environment:
  matrix:
  # executable w/o debug symbols
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    PATH: C:\Python37-x64;%PATH%
    DEBUG: NO
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    PATH: C:\Python35-x64;%PATH%
    DEBUG: NO
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    PATH: C:\Python35-x64;%PATH%
    DEBUG: NO

  # executable w/ debug symbols
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    PATH: C:\Python37-x64;%PATH%
    DEBUG: YES
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    PATH: C:\Python35-x64;%PATH%
    DEBUG: YES
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    PATH: C:\Python35-x64;%PATH%
    DEBUG: YES

build_script:
  - cmd: python -V
  - cmd: python build_crasher.py
  - cmd: python setup.py build_ext -i
  - cmd: dir

test_script:
  - cmd: python -m ci_core_dumper -v install
  - cmd: reg query "HKLM\Software\Microsoft\Windows NT\CurrentVersion\AeDebug"
  - cmd: reg query "HKLM\Software\Wow6432Node\Microsoft\Windows NT\CurrentVersion\AeDebug"
  - cmd: python test_crasher.py
  - cmd: python -m ci_core_dumper crash
  - cmd: python -m ci_core_dumper -v uninstall
  - cmd: python -m ci_core_dumper -v report

on_finish:
  - cmd: dir "C:\Users\appveyor\AppData\Local\Temp\1\cores"

notifications:
  - provider: GitHubPullRequest
