os: linux
language: python

addons:
  apt:
    packages:
    - gdb

script:
  - python -V
  - sudo python -m ci_core_dumper -v install
  - ulimit -c unlimited
  - python build_crasher.py
  - python test_crasher.py
  - python -m ci_core_dumper crash
  - sudo python -m ci_core_dumper -v uninstall
  - python -m ci_core_dumper -v report

matrix:
  include:
    - python: "2.7"
      env: DEBUG=NO
    - python: "3.7"
      env: DEBUG=NO
    - python: "2.7"
      env: DEBUG=YES
    - python: "3.7"
      env: DEBUG=YES
