os: linux
language: python
python: "2.7"

addons:
  apt:
    packages:
    - gdb

script:
  - sudo python -m ci_core_dumper install
  - ulimit -c unlimited
  - python build_crasher.py
  - ./crasher abort || true
  - ./crasher crash || true
  - sudo python -m ci_core_dumper uninstall
  - python -m ci_core_dumper report
